# Disable Docker stuff to try to make it faster
sudo: true
dist: bionic

# Choose a lightweight base image; we provide our own build tools.
language: generic

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
  #- env: CHECK_SCRIPT="./etc/ci-script.sh"
  - env: CHECK_SCRIPT="./etc/curator-2-check.sh"

# Edit etc/ci-script.sh to change GHC version
script:
- $CHECK_SCRIPT

# Caching doesn't work with sudo: true
#cache:
#  directories:
#    - $HOME/.stack
#    - $HOME/.stackage/curator/cache
